import pygame

# Game Name
GAME_TITLE = 'Gobbo Hunt'

# Display Size
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600

# Color Schema
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_GREY = (100, 100, 100)
COLOR_GREEN = (7, 197, 45)

# Color Variables
STARTSCREEN_BG_COLOR = COLOR_BLACK
STARTSCREEN_TITLE_COLOR = COLOR_GREEN
STARTSCREEN_SPACEBAR_COLOR = COLOR_WHITE
